### ISSUE TITLE
img_check.sh: Ignore the file /var/log/cpanel-install.log

### ISSUE THREAD

**Issue by cPanelScott** [digitalocean/marketplace-partners#75] opened 2019-09-17 19:29 UTC
When we install cPanel on a server, we automatically place a log of the installation process at `/var/log/cpanel-install.log`. This file is then used later on by our customers or our support staff to troubleshoot problems. Currently, `img_check.sh` flags this file, and emits a warning. Our customer base and support staff have come to expect this file here. Can you please modify `img_check.sh` to ignore `/var/log/cpanel-install.log` so that it no longer returns a warning and exits with a `0` status (assuming all other tests pass, of course).

Thank you!

**Comment by ryanpq** [comment] 2019-09-25 15:07
A check has been added to the loops reviewing log files to ignore the existence of the cpanel-install.log and merged.

**Closed** 2019-09-25 15:07 UTC

**Comment by cpanelrikus** [comment] 2019-09-25 17:29
Hi Ryan—It looks like the check was added to the two loops for archived logs (patterns `/var/log/*-????????` and `/var/log/*.[0-9]`) but not to the main check for regular log files (`/var/log/*.log`).

We're still getting the warning:

```
[root@terraform-bce7712c-f753-4e55-1f05-1a6c16670f6b centos]# curl -qs https://raw.githubusercontent.com/digitalocean/marketplace-partners/master/scripts/img_check.sh | bash - | grep cpanel-install
[WARN] un-cleared log file, /var/log/cpanel-install.log found
[root@terraform-bce7712c-f753-4e55-1f05-1a6c16670f6b centos]# 
```

I don't think it's actually possible for the current `if (( $f != $cp_ignore)); then` checks to ever have an impact because the two loops only pick up files whose names end in a hyphen followed by 8 characters or a dot followed by a single digit, and the `cp_ignore` string doesn't fit either of those patterns. Since those checks appear to be ineffective anyway, would it be possible to undo those and instead add the check to the `for f in /var/log/*.log; do` loop below them?

Thanks for your help with this.

**Comment by ryanpq** [comment] 2019-09-25 17:42
That was a mistake on my part.  I was testing the script changes by copy/pasting the script to a test system and once everything was working committed the change.  What I failed to do was first save the changes before committing.  A new commit has been merged with this fixed.

**Comment by cpanelrikus** [comment] 2019-09-25 17:57
Cool, thanks! I tested and confirmed that it's working as expected now.
